#!/usr/bin/python
import socket
import sys
import optparse

opts = optparse.OptionParser(usage="%s [ options ] <command>" % sys.argv[0])
opts.add_option(
	"-s","--socket",
	dest="socket",
	metavar="path",
	help="Socket to connect to",
	default="/var/run/darklistd"
	)
(options, args) = opts.parse_args()

if len(args) < 1:
	opts.print_help()
	sys.exit(1)

sock = options.socket

cmd = " ".join(args)+"\n"

s=socket.socket(socket.AF_UNIX,socket.SOCK_STREAM,0)
try:
	s.connect(sock)
except socket.error, e:
	print >> sys.stderr, "Failed to open unix socket (%s - %s)" % (sock, e[1])
	print >> sys.stderr, " - Is darklistd running ?"
	sys.exit(1)
	
s.send(cmd)
while 1:
	f=s.recv(1024)
	if f=="":
		break
	sys.stdout.write(f)
print
s.close()
